### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by seyeeet** [EricGuo5513/action-to-motion#2]
Do you think it is possible to provide the code for the visualization that is provided in the paper:

like 
![image](https://user-images.githubusercontent.com/62394093/92166017-e906b700-ee05-11ea-8598-129d2973815e.png)

or this:

![image](https://user-images.githubusercontent.com/62394093/92166050-fa4fc380-ee05-11ea-829f-b7bec985f77e.png)

**Comment by EricGuo5513** [comment]
About visualization you could use the function plot_3d_pose_v2 in
utills/plot_script.py for plotting poses, or function plot_3d_motion_v2 for
short video (.gif) animations.

Sey Eeet <notifications@github.com> 于2020年9月3日周四 下午2:53写道：

**Comment by EricGuo5513** [comment]
Hi seyseet,
If you want to plot the semi-nude 3d model like the second figure, you may need to render the 3d poses into SMPL models.
