### ISSUE TITLE
Could you tell me how to fit the results of VAE (3d Keypoints) to the SMPL model?

### ISSUE THREAD

**Issue by wonjun-chung** [EricGuo5513/action-to-motion#3]
Could you explain how to fit the results of VAE (3d Keypoints) to the SMPL model?
Is there any code for doing this?

**Comment by EricGuo5513** [comment]
Hi wonjun, thanks for your interests on our work. We use the original SMPLify model fitting code. For your reference: http://smplify.is.tue.mpg.de/downloads and https://github.com/nkolot/SPIN/tree/master/smplify
