### ISSUE TITLE
Wrong FID calclulation

### ISSUE THREAD

**Issue by atnikos** [EricGuo5513/action-to-motion#7]
Hey, thanks for the nice work!
One thing I have observed is that the FID calculation is wrong:
[here](https://github.com/EricGuo5513/action-to-motion/blob/190b80f587b4dc984cd8c1e9d14fcf3ef111b299/eval_scripts/final_evaluation.py#L52) you are passing to the function `(gt, generated)` features for FID calculation.
However the `frechet distance function` accepts the arguments in the [reversed order](https://github.com/EricGuo5513/action-to-motion/blob/190b80f587b4dc984cd8c1e9d14fcf3ef111b299/eval_scripts/fid.py#L5) which if you do results in different number.

**Comment by EricGuo5513** [comment]
Hi, sorry for the late reply. Thanks for pointing it out. That does make some differences.

**Comment by atnikos** [comment]
Hey, I don't think it is a problem in your case this problem occurs if you normalize the features before you apply frechet distance, which I don't think you do. Otherwise, Frechet Distance is commutative and does not cause any difference in the results.
