### ISSUE TITLE
About gradient computation wrong in torch1.10

### ISSUE THREAD

**Issue by yewenkai** [EricGuo5513/action-to-motion#8]
If i use torch1.3 or 1.4, my gpu can't run cuda, so i use 'torch-1.10.2+cu113-cp38-cp38-linux_x86_64.whl'(for convience, i use the [ACTOR's](https://github.com/Mathux/ACTOR) environment, but change the torch version)

I try to train CMU Mocap.
If i don't use lie
`python train_motion_vae.py --name cmutry --dataset_type mocap  --batch_size 128 --motion_length 100 --lambda_kld 0.01 --eval_every 2000 --plot_every 50 --print_every 20 --save_every 2000 --save_latest 50 --time_counter  --gpu_id 0 --iters 50000 `
it fine,
but if i use lie as following:
`python train_motion_vae.py --name cmutrylie --dataset_type mocap  --batch_size 128 --motion_length 100 --lambda_kld 0.01 --eval_every 2000 --plot_every 50 --print_every 20 --save_every 2000 --save_latest 50 --time_counter --use_lie --gpu_id 0 --iters 50000 `

I got the wrong about gradient computation

so i add`torch.autograd.set_detect_anomaly(True)`in vae_trainer.py > Trainer > train

then i got this (i change the code, so the line may not same as your version in github)
`[W python_anomaly_mode.cpp:104] Warning: Error detected in BmmBackward0. Traceback of forward call that caused the error:
  File "train_motion_vae.py", line 108, in <module>
    logs = trainer.trainIters(prior_net, posterior_net, decoder)
  File "/home/ac/ywk/KGAN/action-to-motion-master/trainer/vae_trainer.py", line 233, in trainIters
    gen_log_dict = self.train(prior_net, posterior_net, decoder, self.opt_prior_net, self.opt_posterior_net,
  File "/home/ac/ywk/KGAN/action-to-motion-master/trainer/vae_trainer.py", line 121, in train
    mse = mse + self.recon_criterion(x_pred, data[:, i])
  File "/home/ac/ywk/KGAN/action-to-motion-master/trainer/vae_trainer.py", line 331, in mse_lie
    generated_joints = self.pose_lie_2_joints(lie_param, real_joints)
  File "/home/ac/ywk/KGAN/action-to-motion-master/trainer/vae_trainer.py", line 347, in pose_lie_2_joints
    pose_joints = self.lie_to_joints(lie_params, pose_batch, root_translation)
  File "/home/ac/ywk/KGAN/action-to-motion-master/trainer/vae_trainer.py", line 352, in lie_to_joints
    joints = self.lie_skeleton.forward_kinematics(lie_params, joints, root_translation) 
  File "/home/ac/ywk/KGAN/action-to-motion-master/lie/pose_lie.py", line 97, in forward_kinematics
    joints[:, chain[i], :] = torch.matmul(matR, translation_vec).squeeze_()\
 (function _print_stack)
Traceback (most recent call last):
  File "train_motion_vae.py", line 108, in <module>
    logs = trainer.trainIters(prior_net, posterior_net, decoder)
  File "/home/ac/ywk/KGAN/action-to-motion-master/trainer/vae_trainer.py", line 233, in trainIters
    gen_log_dict = self.train(prior_net, posterior_net, decoder, self.opt_prior_net, self.opt_posterior_net,
  File "/home/ac/ywk/KGAN/action-to-motion-master/trainer/vae_trainer.py", line 133, in train
    losses.backward()
  File "/home/ac/anaconda3/envs/actor/lib/python3.8/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/ac/anaconda3/envs/actor/lib/python3.8/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [128, 3, 1]] is at version 38; expected version 37 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!`

I fix the problem by rewrite.   file <pose_lie.py>  [  line 95](https://github.com/EricGuo5513/action-to-motion/blob/190b80f587b4dc984cd8c1e9d14fcf3ef111b299/lie/pose_lie.py#L95)  (in your github version)

`translation_vec = translation_mat[:, chain[i], :].unsqueeze_(-1).clone().detach().to(joints.device)`
it can run, but very slowly.

Output show :

`3m 29s (- 8720m 48s) niter: 20 completed:   0%) g_loss: 1.039  g_recon_loss: 1.026  g_kld_loss: 1.275`

but in the no use lie version,only 1/10 time consuming, only about 890min.
Is this time consuming right in the GPU RTX 3090?

Thank you!

**Comment by EricGuo5513** [comment]
Hi, sorry for the late reply. Using lie does slow down the training process. Usually it takes 1-2 days to finish 50000 iterations. Could you make sure that GPU is utlized?

**Comment by yewenkai** [comment]
> Hi, sorry for the late reply. Using lie does slow down the training process. Usually it takes 1-2 days to finish 50000 iterations. Could you make sure that GPU is utlized?

Thank you for your reply. I'm sure that GPU is in use. 
I think the reason why the training slows down is that I modified the [<pose_lie.py>](https://github.com/EricGuo5513/action-to-motion/blob/190b80f587b4dc984cd8c1e9d14fcf3ef111b299/lie/pose_lie.py#L95) and transferred the data between GPU and CPU during the operation.
